name: hotelbooking_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - mlflow
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - joblib
